profileMode:
  enabled: true
  subtitle: "This is subtitle"
  imageUrl: "image/elephant.png" 
  imageTitle: "Little Bitta Logo" 
  buttons:
    - name: Archive
      url: "/archive"
    - name: Github
      url: "https://github.com/louislef299"

socialIcons: 
  - name: github
    url: "https://github.com/louislef299"

hideFooter: false
defaultTheme: auto
disableThemeToggle: true
disableScrollToTop: true

label:
  icon: "image/purple-elephant.png"
  text: Little Bitta Bakes
  iconHeight: 40px

# You can add testimonials once the customer base increases
# testimonials:
#    - tweet: https://twitter.com/Canelo/status/1655275902010359814?cxt=HHwWjIC8ibaq3PgtAAAA
#   - author: Louis Lefebvre
#     from: Fictional Incorporated
#     content: >
#               This is the best granola you will ever have!
